### ISSUE TITLE
Create Container from Different PC

### ISSUE THREAD

**Issue by Younes-Charfaoui** [HouariZegai/FlyingAgent#1]
At this moment when we try to create a container from Houari PC, the container is created and then is disappear suddenly, the Main Container indicate that the created container is unreachable.

here is the command used to create Container from different PC.

`java jade.Boot -container -host 192.168.43.36 -port 1099`

Thanks a lot.

**Comment by Younes-Charfaoui** [comment]
## Wired PC

This Issue is solved after testing on PC's that are wired together in the same router, this time no unreachable, and even more, I could create Dummy agent from my PC in the other one.

Here is the command:
`java jade.Boot -container -host 192.168.1.36 -port 1099 -local-port 1234`
`local-port` mean the new container port  and `port` mean the main container port.
At this moment we have to develop using router and wired PC's.

**Comment by HouariZegai** [comment]
Disable the firewall and try again with wireless.

**Comment by Younes-Charfaoui** [comment]
Ok then, I will try this afternoon Inshallah.

**Comment by Younes-Charfaoui** [comment]
# Solved

After Disabling the Firewall I have been authorized to reach the remote container, and even more, without disabling the firewall I also could reach it by allowing some rule in the firewall for the Java platform things, the way to do that is by going to the Control Panel / Windows Defender FireWall  and then form the sidebar go to advanced settings then check the rules in the inbound and outbound section, and allow the program that "Java(TM) 2 Platform Standard Edition binary "

Then run the Main container and specify the host it will be running on otherwise jade will create a virtual one, the on the other host create a peripheral container and specify the host and port of the main container, and the local-port of this created container.
