### ISSUE TITLE
Starting Window

### ISSUE THREAD

**Issue by Younes-Charfaoui** [HouariZegai/FlyingAgent#4]
@HouariZegai  Khas el tsawir ta3 starting, w bghte nsa9sik ida ki yedrak 3la el ScannAll, tbanli mayrohech nichan el Agent, nediro fel window li tekhroj start scann wila haja kimen haka, Wesh Rayek ?

**Comment by HouariZegai** [comment]
Wah idée mli7a, dok n modifier 3liha
