### ISSUE TITLE
App Starting

### ISSUE THREAD

**Issue by Younes-Charfaoui** [HouariZegai/FlyingAgent#7]
Houari Salamo, Winma n9ala3 el application tjiini boucle infini ta3 hadi el error

`Mar 07, 2019 1:21:46 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.171 by JavaFX runtime of version 8.0.71`

aya w tg3od ghi tet3awed hado les lignes, chof m3aha nakhayek.

**Comment by HouariZegai** [comment]
Slm, Hmdlh fixed :D.

**Comment by Younes-Charfaoui** [comment]
@HouariZegai  rani sobte el error win rahi, teba3 melih chta rah yesra
fel main controller rak tedir hadi bah tloadi View
`FXMLLoader scanEachLoader = new FXMLLoader(getClass().getResource("/resources/views/ScanEach.fxml"));
            scanEachView = scanEachLoader.load();`

apres hadi ghadi nlonci intilisize ta3 ScanEach W ScanAll, teba3 f scan each w scan All chta kayen;

`       try {
            mainView = FXMLLoader.load(getClass().getResource("/resources/views/Main.fxml"));
        } catch(IOException ioe) {
            ioe.printStackTrace();
        }`

hadi ghadi t3awed nlonci initilize ta3 main li ghadi t3awed tcriyi scan each w scan all w hiya rayha, 3labiha ga3dte tesra diik ta3 infini, chof kifah tedirelha houari

**Comment by HouariZegai** [comment]
You didn't **pull**  the changes, i fixed the bug yesterday -_-

**Comment by HouariZegai** [comment]
You didn't **pull**  the changes, i fixed the bug yesterday -_-

**Comment by Younes-Charfaoui** [comment]
hhhhhhhhhhhhhhh hahdar houari khouyaa, goli pulli w 3awed siyi 😂😂😂
